### PR TITLE
Use output filename

### PR DESCRIPTION
**Pull request by WashingtonJunior**
PrusaSlicer 2.4 and newer uses a temporary filename (a numbered one), before creating the final file. As a result, files uploaded to SD card doesn't have the same name as we saved (causing confusion when you need to use a previously saved GCode). This fix uses the final output filename for uploading (like it worked before 2.4).

### CODE REVIEW

**Comment by ArtificalSUN** [comment]
Could you please test the latest release with your changes? If it works as intended (or at least is not fatally broken), then I'll merge your changes to the latest relese. If not, then I'll figure something out, maybe i'll merge it with the old version to create separate version.

**Comment by WashingtonJunior** [comment]
> Could you please test the latest release with your changes? If it works as intended (or at least is not fatally broken), then I'll merge your changes to the latest relese. If not, then I'll figure something out, maybe i'll merge it with the old version to create separate version.

Sure, I'll test it right now and I'll let you know.

**Comment by WashingtonJunior** [comment]
Same issue with the new version (look at filename, which it's not what I've saved):


But the same fix applies also (right filename now):


I just uploaded the new version fixed to GitHub and I'll open a new PR.

Thanks!

**Comment by WashingtonJunior** [comment]
I believe I don't need to create a new PR, right? If you merge it now it will used the last version I commited?

Thanks!

**Comment by ArtificalSUN** [comment]
I've merged your changes, thank you!

**Pull request merged**
